[package]
name = "vita-input"
version = "0.2.1"
edition = "2021"
description = "A crate for handling input on the PlayStation Vita."
repository = "https://github.com/exotik850/vita-input"
license = "MIT"

[dependencies]
glam = { version = "0.32.1", optional = true }
vitasdk-sys = { version = "0.3" }

[features]
default = ["controller", "touch"]
glam = ["dep:glam"]
bindgen = ["vitasdk-sys/bindgen"]
controller = ["vitasdk-sys/SceCtrl_stub"]
touch = ["vitasdk-sys/SceTouch_stub"]